### ISSUE TITLE
General questions about the patch

### ISSUE THREAD

**Issue by casasfernando** [CookiePLMonster/SilentPatchNFS90s#5] opened 2024-04-09 06:01 UTC
I found this patch while trying to get NFS2SE and NFS3HP working on Linux through Wine and I was wondering about the following:

1. Would this patch work if executed in Wine?
2. How does the patch work? Does it patch the game’s exe file or it does some kind of “on-the-fly” patching after the game’s exe file is loaded?
3. If it doesn’t patch the game’s exe file, would it be possible to do so some how (e.g.: via hex editor) to get the same fixes?

The main problem I have with both games is related to CPU affinity, documented in this Wine bug: https://bugs.winehq.org/show_bug.cgi?id=11317

Thanks

**Comment by CookiePLMonster** [comment] 2024-04-09 11:12
> 1. Would this patch work if executed in Wine?

Yes, although it may need some extra setup. See: https://cookieplmonster.github.io/setup-instructions/#proton-wine



> 2\. How does the patch work? Does it patch the game’s exe file or it does some kind of “on-the-fly” patching after the game’s exe file is loaded?

It loads into the process with Ultimate ASI Loader and then performs patches on the fly. The game files remain untouched.



> 3\. If it doesn’t patch the game’s exe file, would it be possible to do so some how (e.g.: via hex editor) to get the same fixes?

Not for the most part, because most of those fixes add code, rather than just patching the existing functions. It's still be technically possible, but I don't consider it worth the effort considering how versatile the current approach is.

**Comment by casasfernando** [comment] 2024-04-09 11:28
Thanks for your reply.
I will try your patch with NFS2SE and NFS3HP and see if it helps to workaround Wine's bug I mentioned above (I'm not installing any other modern patches or anything btw).

If I understand correctly all I need to do is:

1. extract all the files into the game folder (next to the game's exe) inside the Wine prefix
2. create an ini file with the same name as the game's exe and add the following single line (no `[header-section]`?): `SingleProcAffinity=1`
3. create an override with winecfg for `dinput.dll` with `(native, builtin)` suffix
4. cross my fingers and launch the game's exe as usual

**Comment by CookiePLMonster** [comment] 2024-04-09 11:31
The Wine instructions are not mine so I never confirmed them, but that sounds correct. However, you shouldn't need to do 2. as by default SP applies reasonable affinity settings that should work fine. This option exists only in case I missed something and affinity needs to be pinned in a more generic manner.

**Comment by casasfernando** [comment] 2024-04-09 11:35
Ok, thanks for clarifying. I will try without 2. first and revert to 2. if it doesn't work.
Just out of curiosity, the dll is used as a mean to load the patch or I'm wrong?

**Comment by CookiePLMonster** [comment] 2024-04-09 11:36
Yes, `dinput.dll` shipped is https://github.com/ThirteenAG/Ultimate-ASI-Loader.

**Comment by casasfernando** [comment] 2024-04-09 11:39
Thanks for your answers!

I will try this out later today. I really hope it works. :smile:

**Comment by CookiePLMonster** [comment] 2024-04-09 11:40
Enjoy! I will close this issue for now, if you run into any problems feel free to reopen.

**Comment by casasfernando** [comment] 2024-04-09 17:07
So I tried the patch with NFS2SE to no avail. :disappointed: 
Same error as reported in Wine bug above.
I tried with and without the ini file and double checked that the dinput library override is in place with winecfg.

@CookiePLMonster  Just to confirm I didn't miss anything would you mind checking that I got the file names correctly for the .asi and .ini files?

```
drwxrwxr-x  4 fernando fernando    4096 abr  9 18:56  ./
drwxrwxr-x  3 fernando fernando    4096 abr  7 20:47  ../
-rw-rw-r--  1 fernando fernando   89658 abr  7 20:48  DeIsL1.isu
-rw-rw-r--  1 fernando fernando 2209280 jun 28  2023  dinput.dll
-rw-rw-r--  1 fernando fernando  127488 jul 14  1997  dsetup.dll
-rw-rw-r--  1 fernando fernando    9216 sep 12  1997  eacsnd.dll
drwxrwxr-x  3 fernando fernando    4096 abr  7 20:47  FeData/
drwxrwxr-x 12 fernando fernando    4096 abr  7 20:47  GameData/
-rw-rw-r--  1 fernando fernando      37 sep 15  2023  global.ini
-rw-rw-r--  1 fernando fernando     782 abr  7 20:47  install.win
-rw-rw-r--  1 fernando fernando    4655 sep 24  1997  license.txt
-rw-rw-r--  1 fernando fernando  105984 sep 23  2023  nfs2sea.asi
-rwxrwxr-x  1 fernando fernando  975360 sep 22  1997  nfs2sea.exe*
-rw-rw-r--  1 fernando fernando     766 sep  2  1997  nfs2sea.ico
-rw-rw-r--  1 fernando fernando      21 abr  9 18:55  nfs2sea.ini
-rw-rw-r--  1 fernando fernando  105984 sep 23  2023  nfs2sen.asi
-rwxrwxr-x  1 fernando fernando  900096 sep 22  1997  nfs2sen.exe*
-rw-rw-r--  1 fernando fernando     766 ago 28  1997  nfs2sen.ico
-rw-rw-r--  1 fernando fernando      21 abr  9 18:56  nfs2sen.ini
-rw-rw-r--  1 fernando fernando     766 sep  2  1997  nfs2ser.ico
-rw-rw-r--  1 fernando fernando     823 abr  7 20:47  NFSIIse.lnk
-rwxrwxr-x  1 fernando fernando  455680 sep 12  1997  patch.exe*
-rw-rw-r--  1 fernando fernando  119808 ago 22  1997  patchw32.dll
-rw-rw-r--  1 fernando fernando   17447 sep 24  1997  readme.txt
-rw-rw-r--  1 fernando fernando  141652 ago 19  1997  shell.dll
-rw-rw-r--  1 fernando fernando     495 abr  7 20:47 'Uninstall Need For Speed II SE.lnk'
```
Both nfs2sea.ini and nfs2sen.ini contains the same line:
```
SingleProcAffinity=1
```
And as said I tried first without the ini files, and then with them.

Thanks

**Comment by CookiePLMonster** [comment] 2024-04-09 17:12
ASI files don't need to be renamed. For the ini, you're missing the section name - `[NFS2SEA]` and `[NFS2SEN]` respectively.

**Comment by casasfernando** [comment] 2024-04-09 17:13
> ASI files don't need to be renamed. For the ini, you're missing the section name - `[NFS2SEA]` and `[NFS2SEN]` respectively.

Sorry I thought they did. I will fix this and try again.

Thanks

**Comment by casasfernando** [comment] 2024-04-09 17:28
So I made the changes to both the patch file name:
```
drwxrwxr-x  4 fernando fernando    4096 abr  9 19:22  ./
drwxrwxr-x  3 fernando fernando    4096 abr  7 20:47  ../
-rw-rw-r--  1 fernando fernando   89658 abr  7 20:48  DeIsL1.isu
-rw-rw-r--  1 fernando fernando 2209280 jun 28  2023  dinput.dll
-rw-rw-r--  1 fernando fernando  127488 jul 14  1997  dsetup.dll
-rw-rw-r--  1 fernando fernando    9216 sep 12  1997  eacsnd.dll
drwxrwxr-x  3 fernando fernando    4096 abr  7 20:47  FeData/
drwxrwxr-x 12 fernando fernando    4096 abr  7 20:47  GameData/
-rw-rw-r--  1 fernando fernando      37 sep 15  2023  global.ini
-rw-rw-r--  1 fernando fernando     782 abr  7 20:47  install.win
-rw-rw-r--  1 fernando fernando    4655 sep 24  1997  license.txt
-rwxrwxr-x  1 fernando fernando  975360 sep 22  1997  nfs2sea.exe*
-rw-rw-r--  1 fernando fernando     766 sep  2  1997  nfs2sea.ico
-rw-rw-r--  1 fernando fernando      33 abr  9 19:15  nfs2sea.ini
-rwxrwxr-x  1 fernando fernando  900096 sep 22  1997  nfs2sen.exe*
-rw-rw-r--  1 fernando fernando     766 ago 28  1997  nfs2sen.ico
-rw-rw-r--  1 fernando fernando      33 abr  9 19:15  nfs2sen.ini
-rw-rw-r--  1 fernando fernando     766 sep  2  1997  nfs2ser.ico
-rw-rw-r--  1 fernando fernando     823 abr  7 20:47  NFSIIse.lnk
-rwxrwxr-x  1 fernando fernando  455680 sep 12  1997  patch.exe*
-rw-rw-r--  1 fernando fernando  119808 ago 22  1997  patchw32.dll
-rw-rw-r--  1 fernando fernando   17447 sep 24  1997  readme.txt
-rw-rw-r--  1 fernando fernando  141652 ago 19  1997  shell.dll
-rw-rw-r--  1 fernando fernando  105984 sep 23  2023  SilentPatchNFS90s.asi
-rw-rw-r--  1 fernando fernando     495 abr  7 20:47 'Uninstall Need For Speed II SE.lnk'
```
and the ini files content:
```
[NFS2SEA]
SingleProcAffinity=1
```

And tried both, with and without the ini files, to no joy. :disappointed: 

Thanks for trying to help but it seems I will have to wait for Wine team to fix the bug, if that ever happens, or just use the modern wrapper.

One last question. Is there any way for the patch to generate a log file at least to confirm that it indeed is being loaded?

**Comment by CookiePLMonster** [comment] 2024-04-09 17:30
> One last question. Is there any way for the patch to generate a log file at least to confirm that it indeed is being loaded?

There isn't, but if you are able to peek at the loaded modules/DLLs, it'll show there if it has loaded.

**Comment by casasfernando** [comment] 2024-04-09 17:33
Ok. I will try to confirm through Wine logs or something, if possible.

Thanks!

**Comment by casasfernando** [comment] 2024-04-09 18:04
I think the patch is loaded because I found this in Wine logs (I can share the full 250 lines if you wish):

```
0024:trace:loaddll:build_module Loaded L"C:\\Program Files\\Electronic Arts\\Need For Speed II SE\\DINPUT.dll" at 10000000: native
.....
0024:trace:loaddll:build_module Loaded L"C:\\Program Files\\Electronic Arts\\Need For Speed II SE\\SilentPatchNFS90s.asi" at 01610000: native
```

Just not working as expected.

**Comment by CookiePLMonster** [comment] 2024-04-10 09:22
It could just be that Wine is hitting/exposing another threading bug I didn't fix. In my experience, NFS2SE was pretty fragile.

**Comment by casasfernando** [comment] 2024-04-10 09:46
If interested I can try to test the patch with NFS3HP tonight to see if behaves any differently.
I know NFS3HP suffers from the same issue in Wine but maybe your patch can produce a different result with that one?

Based on what I've read in Wine bug report and other places, it seems that threads go into a deadlock caused by Wine running them on different CPUs on SMP machines.
What I'm not sure is if Wine will pay any attention on the application affinity or it will just completely ignore it because I even tried to use the imagecfg.exe tool to set the exe itself to run on only one CPU (-u), but this didn't work either.
According to the bug, forcing the Wine process itself to run on only one CPU works around the problem but I tried this myself with the same results.

For what it worth, I have NFSHS and NFSPU both running on Wine without any issues and without any patches.

**Comment by casasfernando** [comment] 2024-04-10 10:12
I'm also pending to test if the problem is related with ddraw.dll.
According to this Wine bug: https://bugs.winehq.org/show_bug.cgi?id=4487
It may be related and will test this alternative [replacement](https://github.com/FunkyFr3sh/cnc-ddraw) to see if it helps to at least run the games in software mode.

**Comment by casasfernando** [comment] 2024-04-10 21:04
Using a replacement ddraw.dll as I mentioned in my previous comment didn't help. The deadlock still happens.
So in a nutshell nor the silent patch or a replacement dll for ddraw worked so far to play the game through Wine.

On the other I was able to use schedtool to launch the game forcing Wine itself to run on only one CPU as suggested in Wine's bug report (for some reason this didn't work for me in the past so I was probably doing something wrong) and this works for both software and 3dfx mode.

Thanks for your answers. I will close the issue now as the problem is Wine related really and the schedtool workaround seems to work.

**Closed as completed** 2024-04-10 21:43 UTC
